package com.app.decisioniq.llm;

public enum QuestionIntent {

    EXPLAIN_TRANSACTION_DECISION,
    EXPLAIN_APPROVAL,
    EXPLAIN_DECLINE,
    EXPLAIN_REVIEW,

    SHOW_TRANSACTION_SUMMARY,
    SHOW_MODEL_SCORE,
    SHOW_RULE_FIRED,
    SHOW_REASON_CODES,
    SHOW_RISK_BAND,

    SHOW_CUSTOMER_HISTORY,
    COMPARE_WITH_CUSTOMER_HISTORY,

    SHOW_DMP_TRACE,
    SHOW_GENERATED_FEATURES,

    FIND_SIMILAR_CASES,
    FIND_SUSPICIOUS_APPROVALS,

    EXPLAIN_RISK_SIGNALS,

    EXPLAIN_RULE,
    EXPLAIN_POLICY,

    SUBMIT_FEEDBACK,

    CLARIFICATION_REQUIRED,
    UNKNOWN;

    public String toString(){
        return name();
    }

}