package com.app.decisioniq.assistant.dataslice.type;

/**
 * Business-level data slices used by getQuery planning.
 */
public enum DecisionDataSlice {

    TRANSACTION_DECISION_SLICE,
    DECISION_EXPLANATION_SLICE,
    DECISION_CASE_SLICE,
    TRANSACTION_CONTEXT_SLICE,
    DECISION_OUTCOME_SLICE,
    MODEL_SCORE_SLICE,
    RULE_EVALUATION_SLICE,
    REASON_CODE_SLICE,
    RISK_SIGNAL_SLICE,
    CUSTOMER_CONTEXT_SLICE,
    ACCOUNT_CONTEXT_SLICE,
    DMP_TRACE_SLICE,
    GENERATED_FEATURE_SLICE,
    EVALUATION_TRUTH_SLICE
}
